import { registerSW } from 'virtual:pwa-register'

export const updateServiceWorker = registerSW({
  immediate: true,
  onRegisteredSW(_serviceWorkerUrl, registration) {
    // Generated by vite-plugin-pwa. The app shell is cached after a successful
    // first load; user-uploaded dictionaries and generated downloads are not
    // sent to or cached by any remote service.
    registration?.update()
  },
})
